snapshot: work towards better flexibility

diff --git a/.local/bin/snapshot b/.local/bin/snapshot
--- a/.local/bin/snapshot
+++ b/.local/bin/snapshot
@@ -3,72 +3,87 @@
 set -o pipefail
 shopt -s nullglob
 
-dest="$HOME/backup/snapshot"
-gitargs=("--git-dir=$HOME/.dotfiles.git/" "--work-tree=$HOME")
-host="$(hostname)"
-olddir=".snapshot-old"
-
 # state dirs
 state=(.mozilla/firefox/profile .vim/{undo,swap} .gramps .config/transmission-daemon .local/share/zathura .config/mpv/watch_later)
 # state files
-state+=(.viminfo .config/fish/fish_variables .local/share/fish/fish_history .clang-format "$(readlink .wallpaper)")
+state+=(.viminfo .config/fish/fish_variables .local/share/fish/fish_history .clang-format .stignore "$(readlink .wallpaper)")
 # machine specific dirs
 machine=(.config/syncthing .stfolder)
 # machine specific files
-machine+=(.stignore .config/pulse/default.pa)
+machine+=(.config/pulse/default.pa)
 # secret dirs
-secret=(.ssh .gnupg .password-store)
+secret=(.ssh .gnupg)
 
 verbose () { echo "snapshot: $1" >&2 ; }
 die () { echo "snapshot: $1" >&2 ; exit 1 ; }
 
-cd
+while getopts :d:h:o:t: opt; do
+	case "$opt" in
+		d)
+			snapshot_dir="$OPTARG" ;;
+		h)
+			home_dir="$OPTARG" ;;
+		H)
+			host="$OPTARG" ;;
+		o)
+			old_dir="$OPTARG" ;;
+		t)
+			target="$OPTARG" ;;
+		\?)
+			echo "invalid option '-$OPTARG" ;;
+	esac
+done
+
+snapshot_dir=${snapshot_dir:-"$HOME/.snapshot"}
+home_dir=${home_dir:-"$HOME"}
+host=${host:-"$(hostname)"}
+old_dir=${old_dir:-"$HOME/.snapshot-old"}
+target=${target:-/mnt$HOME}
+git_args=("--git-dir=$home_dir/.dotfiles.git/" "--work-tree=$home_dir")
+target_git_args=("--git-dir=$target/.dotfiles.git/" "--work-tree=$target")
+
+cd "$home_dir"
 
 case "$1" in
 push)
-	shift
-
 	# dotfiles
 	verbose "pushing dotfiles"
-	git "${gitargs[@]}" push || die "failed to push dotfiles"
+	git "${git_args[@]}" push || die "failed to push dotfiles"
 
 	# state
 	pkill firefox
 	verbose "archiving state"
-	mkdir -p "$dest" || die "failed to create snapshot destionation - '$dest'"
-	tar -c --zstd -f "$dest/state.tar.zst" "${state[@]}" || die "failed to snapshot state"
-
-	# machine specific
-	verbose "archiving '$host' specific"
-	tar -c --zstd -f "$dest/$host-config.tar.zst" "${machine[@]}" || die "failed to snapshot machine specific"
+	mkdir -p "$snapshot_dir" || die "failed to create snapshot destionation - '$dest'"
+	tar -c --zstd -f "$snapshot_dir/state.tar.zst" "${state[@]}" || die "failed to snapshot state"
 
 	# secret
 	verbose "archiving secret"
-	tar -c --zstd -f - "${secret[@]}" | gpg --yes -c -e --output "$dest/secret.tar.zst.gpg" \
+	tar -c --zstd -f - "${secret[@]}" | gpg --yes -c -e --output "$snapshot_dir/secret.tar.zst.gpg" \
 		|| die "failed to snapshot secret"
-	verbose "success"
+
+	# machine specific
+	verbose "archiving '$host' specific"
+	tar -c --zstd -f "$snapshot_dir/$host-config.tar.zst" "${machine[@]}" || die "failed to snapshot machine specific"
 ;;
 pull)
-	shift
-
 	# dotfiles
 	verbose "pulling dotfiles"
-	git "${gitargs[@]}" pull || die "failed to pull dotfiles"
+	git "${git_args[@]}" pull || die "failed to pull dotfiles"
 
 	# backup
-	mkdir -p "$olddir" || die "failed to create old directory - '$olddir'"
-	verbose "backing up to '$olddir'"
-	mv "${state[@]}" "${secret[@]}" "$olddir" || die "failed to backup state & secret files"
+	mkdir -p "$old_dir" || die "failed to create old directory - '$old_dir'"
+	verbose "backing up to '$old_dir'"
+	mv "${state[@]}" "${secret[@]}" "$old_dir" || die "failed to backup state & secret files"
 
 	# state
 	verbose "killing firefox"
 	pkill firefox
 	verbose "extracting state"
-	tar -x --zstd -f "$dest/state.tar.zst" || die "failed to extract state" || die "failed to extract state"
+	tar -x --zstd -f "$snapshot_dir/state.tar.zst" || die "failed to extract state" || die "failed to extract state"
 
 	# secret
 	verbose "extracting secret"
-	gpg --homedir "$olddir/.gnupg/" --batch -d "$dest/secret.tar.zst.gpg" | tar -x --zstd -f - || die "failed to extract secret"
+	gpg --homedir "$old_dir/.gnupg/" --batch -d "$snapshot_dir/secret.tar.zst.gpg" | tar -x --zstd -f - || die "failed to extract secret"
 
 	verbose "deleting firefox cache"
 	rm -rf .cache/mozilla/firefox || die "failed to delete firefox cache"
@@ -77,16 +92,11 @@ pull)
 	if [[ "$1" == all ]]; then
 		# machine specific
 		verbose "extracting '$host' specific"
-		mv "${machine[@]}" "$olddir" || die "failed to backup '$host' specific"
-		tar -x --zstd -f "$dest/$host-config.tar.zst" || die "failed to extract '$host' specific"
+		mv "${machine[@]}" "$old_dir" || die "failed to backup '$host' specific"
+		tar -x --zstd -f "$snapshot_dir/$host-config.tar.zst" || die "failed to extract '$host' specific"
 	fi
-
-	verbose "success"
 ;;
 bootstrap)
-	shift
-	target="${1:-/mnt$HOME}"
-
 	# clean
 	verbose "cleaning '$target'"
 	shopt -s dotglob
@@ -95,32 +105,29 @@ bootstrap)
 
 	# dotfiles
 	verbose "initializing bare git repository"
-	target_gitargs=("--git-dir=$target/.dotfiles.git/" "--work-tree=$target")
 	git init --bare "$target/.dotfiles.git" || die "failed to initialize bare git repository"
-	git "${target_gitargs[@]}" remote add origin github:lahcim8/dotfiles.git || die "failed to add git remote"
-	git "${target_gitargs[@]}" config status.showUntrackedFiles no || die "failed to set git config option"
+	git "${target_git_args[@]}" remote add origin https://github.com/lahcim8/dotfiles || die "failed to add git remote"
+	git "${target_git_args[@]}" config status.showUntrackedFiles no || die "failed to set git config option"
 	verbose "pulling dotfiles"
-	git "${target_gitargs[@]}" pull --force origin master || die "failed to pull origin"
+	git "${target_git_args[@]}" pull --force origin master || die "failed to pull origin"
+	git "${target_git_args[@]}" remote set-url origin github:lahcim8/dotfiles.git || die "failed to change origin url"
 
 	# extract
 	verbose "extracting to '$target'"
 
 	# state
 	verbose "extracting state"
-	tar -x --zstd -f "$dest/state.tar.zst" -C "$target" || die "failed to extract state" || die "failed to extract state"
+	tar -x --zstd -f "$snapshot_dir/state.tar.zst" -C "$target" || die "failed to extract state" || die "failed to extract state"
 
 	# secret
 	verbose "extracting secret"
-	gpg --batch -d "$dest/secret.tar.zst.gpg" | tar -x --zstd -f - -C "$target" || die "failed to extract secret"
+	gpg --batch -d "$snapshot_dir/secret.tar.zst.gpg" | tar -x --zstd -f - -C "$target" || die "failed to extract secret"
 
 	# machine specific
 	verbose "extracting '$host' specific"
-	tar -x --zstd -f "$dest/$host-config.tar.zst" -C "$target" || die "failed to extract '$host' specific"
-
-	verbose "success"
+	tar -x --zstd -f "$snapshot_dir/$host-config.tar.zst" -C "$target" || die "failed to extract '$host' specific"
 ;;
 confirm)
 	verbose "deleting old"
-	rm -rf "$olddir"
-	verbose "success"
+	rm -rf "$old_dir"
 esac
